application:
  jwt-key: 啊哈，来啦老弟，猜猜密码吧，我打赌你猜不到，嘿嘿嘿嘿嘿嘿嘿
# 正式环境
server:
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 10
  servlet:
    session:
      cookie:
        http-only: true
spring:
  data:
    redis: # redis配置
      host: redis
      port: 6379
      username: default
      password:  # 密码（默认为空）
      database: 0
    timeout: 5s
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 20000
      minimum-idle: 5
      max-lifetime: 120000
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/started?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: e230u42o3og293jskbg3793uhi2bk3

# 日志配置
logging:
  level:
    org:
      mybatis: info
    com:
      example: trace
  file:
    name: log/log.log
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
