# 生产环境
# Tomcat
server:
  port: 80
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 1000
  servlet:
    context-path: /
    session:
      cookie:
        http-only: true
spring:
  redis: # redis配置
    host: redis
    port: 6379
    password:  # 密码（默认为空）
    database: 0
    timeout: 5s
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    druid:
      #MySQL
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://db:3306/db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: 93d295b4f1f9397ca8915a1ae28edd2c
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 6000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      #Oracle需要打开注释
      #validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #login-username: admin
        #login-password: admin
      filter:
        stat:
          log-slow-sql: false
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true
# 日志配置
logging:
  level:
    root: warn
    org.mybatis: warn
    com.example: warn
  file:
    name: log/log.log
