# 公共配置
spring:
  messages:
    encoding: UTF-8
    basename: i18n/messages
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  cloud:
    compatibility-verifier:
      enabled: false
  freemarker:
    suffix: .ftlh
    template-loader-path: classpath:/templates/
    cache: false
    # 编码
    charset: UTF-8
    # Content-Type
    content-type: text/html
    # 检查模板位置
    check-template-location: true
    # 其他配置
    settings:
      datetime_format: yyyy-MM-dd HH:mm:ss
      number_format: 0.##
#  aop:
#    proxy-target-class: true

#mybatis
mybatis-plus:
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.example.modules.*.entity
  global-config:
    #数据库相关配置
    db-config:
      id-type: ASSIGN_ID
    banner: false
  #原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
# 日志配置
logging:
  level:
    org:
      mybatis: debug
    com:
      example: trace
  file:
    name: logs/log.log
