app:
  jwt:
    accessSecret: 01K85GAJVZRZCWX1DSND38JG4701K85GAJVZRZCWX1DSND38JG47CWX1DSND38JG470
    refreshSecret: 01K85GAJVZ0BVS2S9PR7D561P01DSND38JG4701K85GAJVZRZC561P01DSND38JG470

# 日志配置
logging:
  level:
    com:
      example: trace
  file:
    name: logs/log.log

spring:
  messages:
    encoding: UTF-8
  cloud:
    config:
      import-check:
        enabled: false
  data:
    redis:
      client-name:
      host: localhost
      port: 6379
      password:
      database: 0
      timeout: 5s
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 20000
      minimum-idle: 5
      max-lifetime: 120000
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/started?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: e230u42o3og293jskbg3793uhi2bk3
