version: "3.3"
services:
  nginx:
    image: nginx
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/html:/html:ro
    ports:
      - "80:80"
      - "443:443"
  api:
    image: openjdk:21
    restart: unless-stopped
    working_dir: /app
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./app:/app
      - ./app/upload:/upload

    command: java -cp ./jar/lib/* -jar ./jar/com.example.started-api-0.0.1.jar
    ports:
      - "0:8080"
  redis:
    restart: unless-stopped
    image: redis
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./redis/data:/data
      - ./redis/conf:/home/redis
    command: /home/redis/redis.conf
    ports:
      - "6379:6379"
  mysql:
    image: mysql:8.0
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./mysql/init-sql:/docker-entrypoint-initdb.d:ro
      - ./mysql/sql:/opt/sql:ro
      - ./mysql/logs:/var/log/mysql
      - ./mysql/data:/var/lib/mysql
    command: --default-authentication-plugin=caching_sha2_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --lower_case_table_names=1
    restart: unless-stopped
    environment:
      - "MYSQL_ROOT_PASSWORD=jjlanwlnawklnelglgknxlehsnlegll"
      - "MYSQL_DATABASE=started"
      - "TZ=Asia/Shanghai"
    ports:
      - "3306:3306"
#  adminer:
#    image: adminer
#    restart: unless-stopped
#    ports:
#      - 8080:8080
